// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Reserva.API.Data;

#nullable disable

namespace Reserva.API.Migrations
{
    [DbContext(typeof(ReservaAPIContext))]
    [Migration("20260323045310_V01")]
    partial class V01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Reserva.Modelos.Canchas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Tipo_CanchasId")
                        .HasColumnType("integer");

                    b.Property<string>("descripcion_cancha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("estado_cancha")
                        .HasColumnType("boolean");

                    b.Property<string>("nombre_cancha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Tipo_CanchasId");

                    b.ToTable("Canchas");
                });

            modelBuilder.Entity("Reserva.Modelos.Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("apellido_cliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("correo_cliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("fecha_nacimiento_cliente")
                        .HasColumnType("date");

                    b.Property<string>("nombre_cliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("telefono_cliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Reserva.Modelos.Horarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("dia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("hora_fin")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("hora_inicio")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("Reserva.Modelos.Reservas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CanchasId")
                        .HasColumnType("integer");

                    b.Property<int>("ClientesId")
                        .HasColumnType("integer");

                    b.Property<int>("HorariosId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("fecha_reserva")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CanchasId");

                    b.HasIndex("ClientesId");

                    b.HasIndex("HorariosId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Reserva.Modelos.Tipo_Canchas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("nombre_tip_cancha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tipo_Canchas");
                });

            modelBuilder.Entity("Reserva.Modelos.Canchas", b =>
                {
                    b.HasOne("Reserva.Modelos.Tipo_Canchas", "Tipo_Canchas")
                        .WithMany()
                        .HasForeignKey("Tipo_CanchasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tipo_Canchas");
                });

            modelBuilder.Entity("Reserva.Modelos.Reservas", b =>
                {
                    b.HasOne("Reserva.Modelos.Canchas", "Canchas")
                        .WithMany()
                        .HasForeignKey("CanchasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reserva.Modelos.Clientes", "Clientes")
                        .WithMany()
                        .HasForeignKey("ClientesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reserva.Modelos.Horarios", "Horarios")
                        .WithMany()
                        .HasForeignKey("HorariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Canchas");

                    b.Navigation("Clientes");

                    b.Navigation("Horarios");
                });
#pragma warning restore 612, 618
        }
    }
}
